###CREATE A NEW NOTE
POST http://localhost:3000/note
Content-Type: application/json

{
  "title": "My First Note",
  "content": "I am currently learning backend development"
}

###GET ALL NOTES
GET http://localhost:3000/note

###GET A NOTE BY ID
GET http://localhost:3000/note/1

###UPDATE A NOTE BY ID
PATCH http://localhost:3000/note/1
Content-Type: application/json

{
  "title": "Second Note",
  "content": "I am a software developer with strong background in full stack development"
}

###DELETE A NOTE BY ID  
DELETE http://localhost:3000/note/1